#26 Eval footer
GSA/Challenge_platform pull request #113
Opened 2024-08-07 20:47 UTC by bilalhankins

WIP
Added footer to bottom of sandbox
Need to fix some responsiveness and css issues with icons

2024-08-14 00:25 UTC, stepchud commented on app/assets/uswds/_uswds-theme.scss
> -*/
I'd like to keep this comment and maybe remove the "Uncomment the following lines" portion so it just says "Add a list of changed settings in the form $setting: value." for inline documentation

2024-08-14 00:33 UTC, stepchud reviewed
Added commit c877a07 which fixes the social icon SVG issues you were having

2024-08-15 01:21 UTC, stepchud reviewed
I was going to leave some minor UI feedback but it took me a while to play around with the styles and would take longer to explain everything so I added 5b3c86 instead. I think this is close enough to match the mockups. @bilalhankins can you test the responsiveness of this out in your local browser and see if you notice anything else that needs to be fixed?

2024-08-15 02:04 UTC, bilalhankins commented
I tested and the responsiveness is way better than the changes i have locally. The only thing i saw was the space between the GSA logo and the right side of the screen on the mobile view. I tried to see if i could play with the css and eliminate the whitespace. I dont think it is too big of an issue tbh

2024-08-15 05:09 UTC, stepchud commented
> I tested and the responsiveness is way better than the changes i have locally. The only thing i saw was the space between the GSA logo and the right side of the screen on the mobile view. I tried to see if i could play with the css and eliminate the whitespace. I dont think it is too big of an issue tbh

cool, I think it's fixed now

2024-08-15 23:32 UTC, stepchud commented on spec/requests/dashboard_request_spec.rb
> +    it_behaves_like "a page with footer content"
❤️

2024-08-16 00:06 UTC, stepchud requested changes
the internal app links won't work yet but the external ones will. we can go ahead and add all the links now while we build those internal pages. 
copied these from the production site at https://www.challenge.gov

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +                  <a href="javascript:void(0);">About</a>
add link
```suggestion
                  <a href="/about">About</a>
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +                  <a href="javascript:void(0);">Contact</a>
```suggestion
                  <a href="/contact">Contact</a>
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +                  <a href="javascript:void(0);">Terms of use</a>
```suggestion
                  <a href="/terms">Terms of use</a>
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +                  <a href="javascript:void(0);">Privacy Policy</a>
```suggestion
                  <a href="/privacy-policy">Privacy Policy</a>
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +                  <a href="javascript:void(0);">Innovator Resources</a>
```suggestion
                  <a href="/resources">Innovator Resources</a>
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +                  <a href="javascript:void(0);">Agency Resources</a>
```suggestion
                  <a href="/resources-managers">Agency Resources</a>
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +                  <a href="javascript:void(0);">Archived Challenges</a>
```suggestion
                  <a href="/?state=archived">Archived Challenges</a>
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +                  <a href="javascript:void(0);">Active Challenges</a>
```suggestion
                  <a href="/#active-challenges">Active Challenges</a>
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +                  <a href="javascript:void(0);">GSA Privacy Policy</a>
```suggestion
                  <a href="https://www.gsa.gov/website-information/website-policies#privacy">GSA Privacy Policy</a>
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +                  <a href="javascript:void(0);">Accessibility</a>
```suggestion
                  <a href="https://www.gsa.gov/website-information/accessibility-aids">Accessibility</a>
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +                  <a href="javascript:void(0);">FOIA</a>
```suggestion
                  <a href="https://www.gsa.gov/reference/freedom-of-information-act-foia">FOIA</a>
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +                  <a href="javascript:void(0);">USA.gov</a>
```suggestion
                  <a href="https://www.usa.gov/">USA.gov</a>
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +              <a class="usa-social-link" href="javascript:void(0);">
```suggestion
              <a class="usa-social-link" href="https://www.twitter.com/ChallengeGov">
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +              <a class="usa-social-link" href="javascript:void(0);">
```suggestion
              <a class="usa-social-link" href="https://www.facebook.com/ChallengeGov">
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +              <a class="usa-social-link" href="javascript:void(0);">
```suggestion
              <a class="usa-social-link" href="https://www.youtube.com/@challenge-gov">
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +              <a class="usa-social-link" href="javascript:void(0);">
```suggestion
              <a class="usa-social-link" href="https://www.linkedin.com/company/challengegov/">
```

2024-08-16 00:06 UTC, stepchud commented on app/views/layouts/_footer.html.erb
> +              <a class="usa-social-link" href="javascript:void(0);">
```suggestion
              <a class="usa-social-link" href="https://github.com/GSA/Challenge_gov">
```

2024-08-16 16:21 UTC, stepchud approved these changes
think we're g2g 🎉

2024-08-16 16:27 UTC, stepchud commented
WAVE report:
![Screenshot 2024-08-16 at 9 26 05 AM](https://github.com/user-attachments/assets/05fb7c63-e476-45e3-8bfc-e497dafe1658)

2024-08-16 16:57 UTC, merged