[158] Add role-based permission check to routes
GSA/Challenge_platform pull request #174
Opened 2024-09-24 19:45 UTC by cpreisinger

Main tasks
#158 

Role specific sub tasks
#13 
#16 
#23

2024-09-26 01:59 UTC, stepchud requested changes
some feedback mostly on the specs

2024-09-26 01:59 UTC, stepchud commented on .codeclimate.yml
> +- spec/**/*
👍 nice, even codeclimate recommends to [exclude specs/tests](https://docs.codeclimate.com/docs/excluding-files-and-folders#auto-generated-file-and-folder-exclusions) from the quality check

2024-09-26 01:59 UTC, stepchud commented on app/models/user.rb
> +  validates :role, inclusion: { in: ROLES }
on the phx side there are a few admin roles too, shouldn't we include those roles too? atm I'm not sure what those roles can do in the Rails app yet.

2024-09-26 01:59 UTC, stepchud commented on spec/requests/dashboard_request_spec.rb
> -      it_behaves_like "a page with utility menu links for all users"
shouldn't behavior this be kept?

2024-09-26 01:59 UTC, stepchud commented on spec/requests/evaluation_forms_spec.rb
> +      it "renders the index view with the correct header" do
```suggestion
      it "redirects to the phoenix app" do
```

2024-09-26 01:59 UTC, stepchud commented on spec/requests/evaluation_forms_spec.rb
> +      it "renders the index view with the correct header" do
```suggestion
      it "redirects to the dashboard" do
```

2024-09-26 01:59 UTC, stepchud commented on spec/requests/evaluations_spec.rb
> +      it "renders the index view with the correct header" do
```suggestion
      it "redirects to the dashboard" do
```

2024-09-26 01:59 UTC, stepchud commented on spec/requests/evaluations_spec.rb
> +      it "renders the index view with the correct header" do
```suggestion
      it "redirects to the phoenix app" do
```

2024-09-26 01:59 UTC, stepchud commented on spec/requests/manage_submissions_spec.rb
> +      it "renders the index view with the correct header" do
```suggestion
      it "redirects to the dashboard" do
```

2024-09-26 01:59 UTC, stepchud commented on spec/requests/manage_submissions_spec.rb
> +      it "renders the index view with the correct header" do
```suggestion
      it "redirects to the phoenix app" do
```

2024-09-26 01:59 UTC, stepchud commented on spec/requests/evaluations_spec.rb
> +      it "renders the index view with the correct header" do
can we assert the error flash message for these too?

2024-09-26 14:21 UTC, cpreisinger commented on spec/requests/dashboard_request_spec.rb
> -      it_behaves_like "a page with utility menu links for all users"
Solvers go to an entirely different app so it wouldn't be showing the rails utility menu right? That's why I was wondering if the solver utility menu wasn't needed. Or at least not until that is moved over

2024-09-26 16:16 UTC, stepchud commented on spec/requests/dashboard_request_spec.rb
> -      it_behaves_like "a page with utility menu links for all users"
oh my bad, i didn't see that was for public solvers, carry on 👌

2024-09-27 21:46 UTC, stepchud commented on spec/spec_helper.rb
> +  user_attrs = defaults.merge(user_attrs)
can you move these defaults into the `create_user` function, since that's ultimately where they take affect

2024-09-30 16:02 UTC, stepchud approved these changes
LGTM 👍

2024-09-30 16:37 UTC, merged