[283] Eval Form: Cancelation modal
GSA/Challenge_platform pull request #315
Opened 2024-12-10 04:35 UTC by cpreisinger

#283

2024-12-10 17:50 UTC, stepchud requested changes
I like the reusability of this for any other modals that just do confirmation with a redirect, but I think for consistency it should be stimulus. Let me know if that doesn't make sense here or you disagree.

2024-12-10 17:50 UTC, stepchud commented on app/javascript/confirmation_modal.js
> +document.addEventListener("DOMContentLoaded", () => {
can we convert this to a stimulus controller instead? we have a few modal controllers there already.

2024-12-10 17:50 UTC, stepchud commented on app/javascript/confirmation_modal.js
> +      console.log(e);
console.log

2024-12-10 17:54 UTC, stepchud commented on spec/system/evaluation_form_spec.rb
> +    it "shows a confirmation modal when clicking the cancel button" do
nice specs! 🤘

2024-12-11 04:54 UTC, cpreisinger commented
Codeclimate failure for "similar" code blocks in the javascript. Should we suppress this warning?

2024-12-11 21:16 UTC, stepchud commented on app/views/modals/_confirmation.erb
> +  data-modal-cancel-action="<%= defined?(cancel_action) ? cancel_action : '' %>"
nice!

2024-12-11 21:17 UTC, stepchud approved these changes
very 🆒 😎

2024-12-11 21:19 UTC, merged