[82] Submissions List View for Evaluators
GSA/Challenge_platform pull request #319
Opened 2024-12-11 07:22 UTC by emmabjj

User story: #82
Dev tasks: #88, #302, #303

As an evaluator, in order to manage submissions and their evaluations process efficiently, I would like to be able to access submissions assigned to me for each challenge. 

This PR has the following:
- Evaluator can see a list of all challenge phases to which they have been assigned submissions
  - challenge phase title
  - number of submissions "assigned to me"
  - number of submissions "remaining to evaluate"
  - due by date
  - evaluate button that navigates to the list of submissions on that phase
- Evaluator can view a list of submissions they are assigned to evaluate for each challenge
- Evaluation progress summary (assignment stats)
- The list of submissions displays:
  - submission ID
  - My submission evaluation status
  - My score
  - Average score (if all evaluators completed their evaluations)

#### List of challenge phases 
<img width="978" alt="Screenshot 2024-12-11 at 1 07 06 AM" src="https://github.com/user-attachments/assets/b987d98c-4c0d-4f09-a103-030ad204a42d">
<img width="1276" alt="Screenshot 2024-12-11 at 1 06 27 AM" src="https://github.com/user-attachments/assets/704cb6fe-a22c-4571-9db9-e822b51e15c2">

#### List of submissions assigned to the evaluator
<img width="1060" alt="Screenshot 2024-12-11 at 1 10 47 AM" src="https://github.com/user-attachments/assets/c8496dc6-6705-486c-92bc-602c2a263f52">
<img width="1060" alt="Screenshot 2024-12-11 at 1 12 01 AM" src="https://github.com/user-attachments/assets/21e9d87b-89cd-478b-b6c8-74a878627d7c">

#### Mobile
<img width="299" alt="Screenshot 2024-12-11 at 1 18 55 AM" src="https://github.com/user-attachments/assets/d3c08c50-4f47-47a8-8da0-1107196fc548">
<img width="303" alt="Screenshot 2024-12-11 at 1 19 49 AM" src="https://github.com/user-attachments/assets/5b3c3319-393b-4632-8f9c-23595082a429">
<img width="300" alt="Screenshot 2024-12-11 at 1 19 57 AM" src="https://github.com/user-attachments/assets/1d7e5a39-7c6f-465d-9a12-a2cde734238b">

2024-12-13 00:22 UTC, stepchud reviewed
feedback, mostly copy adjustments

2024-12-13 00:22 UTC, stepchud commented on app/controllers/evaluator_submission_assignments_controller.rb
> +  include EvaluationsHelper
This is sort of a quirk in how Rails controllers and Ruby included modules work, but instead of including this module explicitly and adding those helper methods to the controller, it is recommended to use the `helpers` function in the controller.

See: [this SO explanation](https://stackoverflow.com/a/11161692)

In your case, it would be updating calls like `helpers.calculate_submissions_count(assignments)`

2024-12-13 00:22 UTC, stepchud commented on app/controllers/evaluations_controller.rb
> +  include EvaluationsHelper
see other comment about `helpers`

2024-12-13 00:22 UTC, stepchud commented on app/views/shared/_assignment_stats.html.erb
> +          <span class="font-sans-md tablet:font-sans-lg text-success-dark text-bold">Completed</span>
these changes create a low contrast a11y violation at < tablet size. we should keep the `font-sans-lg` at all breakpoints to avoid it (otherwise we need a different status color for the text)

2024-12-13 00:22 UTC, stepchud commented on app/helpers/dashboard_helper.rb
>            subtitle: 'View submissions assigned to me and provide evaluations.' },
Figma was just updated, can you adjust the copy
```suggestion
          subtitle: 'View and evaluate submissions assigned to me.' },
```

2024-12-13 00:22 UTC, stepchud commented on app/helpers/evaluations_helper.rb
> +    Score.new(score, "#{score}%", "#{score}%")
the average score should not have a percent sign after it. the score will not be a percentage for non-weighted-scale scores. figma is inconsistent here but i'm sure we don't want to show a score like "318%". requested clarification on figma.

2024-12-13 00:22 UTC, stepchud commented on app/views/evaluations/_phases_table.html.erb
> +                Evaluate
the figma was updated and now reads "View Submissions"
```suggestion
                View Submissions
```

2024-12-13 00:22 UTC, stepchud commented on app/views/evaluations/submissions.html.erb
> +<p class="text-normal">View challenge submissions and manage evaluation progress.</p>
figma now reads:
```suggestion
<p class="text-normal">View challenges with submissions assigned to me to evaluate.</p>
```
(mobile design is slightly different but let's just use this for now)

2024-12-13 17:42 UTC, stepchud commented on app/helpers/evaluations_helper.rb
> +    Score.new(score, "#{score}%", "#{score}%")
just confirmed, we can remove the % signs from the scores 👍

2024-12-20 19:40 UTC, emmabjj commented
failed test is related to comments in the `evaluation_spec.rb`

2025-01-03 20:12 UTC, stepchud requested changes
Couple of blockers and some other feedback

2025-01-03 20:12 UTC, stepchud commented on spec/helpers/evaluations_helper_spec.rb
> +    it 'returns correct counts for different statuses' do
imo it goes against best practice to mock objects that are being tested directly. this test mostly validates that your mock doubles are setup correctly. with a few exceptions, I'd only use mocks for external/secondary objects that are not directly involved in the current test.

in this case it would be nice to have factories or helper functions that can create assignments/submissions/evaluations in various states of progress/status to make test setup easier and use those instead.

2025-01-03 20:12 UTC, stepchud commented on app/helpers/evaluations_helper.rb
> +    end
this is showing the average score on submissions that are not completed by me and/or by all evaluators. the score should be N/A until *everyone*, myself included, have completed scoring otherwise it can introduce bias in my scoring.
![Screenshot 2025-01-03 at 10 50 15 AM](https://github.com/user-attachments/assets/8ba2f79c-4564-4e63-b8e8-e622b894e964)

2025-01-03 20:12 UTC, stepchud commented on app/helpers/evaluations_helper.rb
> +  end
![Screenshot 2025-01-03 at 11 04 59 AM](https://github.com/user-attachments/assets/37a81212-385d-4e47-992d-86f4ee1ec862)
in the screenshot when I started (id=5) or completed (id=6) an evaluation and then recused myself, this miscounts by including the recused assignments in the `in_progress` or `completed` counts. `recused` assignments should be excluded from the other status counts. you could add the `a.assigned?` status check to all these counts like you did for `#count_not_started`.

2025-01-03 20:12 UTC, stepchud commented on app/views/evaluator_submission_assignments/_unassign_evaluator_submission_modal.html.erb
> +  aria-labelledby="unassign-modal-heading"
NIT: don't change anything here, but some of these view changes are unrelated to the current PR and it makes it harder to review everything together. in the future please try to keep the scope of PRs tight on the tickets at hand to make reviews easier and quicker.

2025-01-03 20:12 UTC, stepchud commented on spec/helpers/evaluators_helper_spec.rb
> +                                               submission: create(:submission, challenge: challenge, phase: phase), status: :recused_unassigned)
update spec name to `recused_unassigned` instead?

2025-01-03 20:12 UTC, stepchud commented on spec/requests/evaluations_spec.rb
> +        end
what is this testing?

2025-01-07 23:11 UTC, emmabjj commented on spec/requests/evaluations_spec.rb
> +        end
This test is now complete. It's testing the submission status count, as well as ensuring that recused submissions are not counted towards the `completed` or `in progress` status counts.

2025-01-08 20:56 UTC, stepchud commented on app/helpers/evaluations_helper.rb
> +    unless completed_evaluations.count == assigned_evaluations.count
I think there is an issue because `completed_evaluations` includes all evaluations with `completed_at: nil` however we only want to calculate and return the average_score for the completed_evaluations that are *also* `assigned` status? you can filter the query
```suggestion
    completed_evaluations = submission.evaluations.where(evaluator_submission_assignment: assigned_evaluations).where.not(completed_at: nil)
    
    unless completed_evaluations.count == assigned_evaluations.count
```

2025-01-08 22:30 UTC, emmabjj commented on app/helpers/evaluations_helper.rb
> +    unless completed_evaluations.count == assigned_evaluations.count
Ahh yep, that makes sense - I'll push that change now, thanks!

2025-01-08 23:30 UTC, emmabjj commented
spec failures are unrelated to this PR

2025-01-09 22:23 UTC, stepchud commented on spec/requests/evaluations_spec.rb
> +    context "when logged in as an evaluator" do
it might be good to have a context `when logged in as an evaluator that is not associated with the challenge phase` to assert access to unrelated phases is denied?

2025-01-09 22:26 UTC, stepchud approved these changes
can you add that new spec from my last comment, and this can be merged? 🚀

2025-01-10 14:39 UTC, merged