[298] Evaluations routes & controller
GSA/Challenge_platform pull request #336
Opened 2024-12-23 23:45 UTC by cpreisinger

#298

2025-01-09 17:03 UTC, stepchud commented
Emma added a way to skip individual specs instead of the whole suite. Can you use that instead of skipping all?
```ruby
it 'renders the index page successfully', bullet: :skip do
  # spec throws the bullet unoptimized exception
end
```

2025-01-09 20:56 UTC, stepchud reviewed
review feedback mostly from our discussions and a few minor details

2025-01-09 20:56 UTC, stepchud commented on app/controllers/evaluations_controller.rb
> +    @evaluation_form = EvaluationForm.find_by(phase:)
nit: save a line?
```suggestion
    @evaluation_form = @evaluator_submission_assignment.phase.evaluation_form
```

2025-01-09 20:56 UTC, stepchud commented on app/controllers/evaluations_controller.rb
> +    redirect_to evaluations_path, alert: I18n.t("evaluations.alerts.unauthorized")
looks like this translation key is missing
```ruby
(ruby) I18n.t("evaluations.alerts.unauthorized")
"Translation missing: en.evaluations.alerts.unauthorized"
```

2025-01-09 20:56 UTC, stepchud commented on config/locales/en.yml
> +      save_draft_error:  "Failed to save evaluation as draft: #{errors}."
typo
```suggestion
      save_draft_error:  "Failed to save evaluation as draft: %{errors}."
```

2025-01-09 20:56 UTC, stepchud commented on app/controllers/evaluations_controller.rb
> +    end
we should redirect back to the original url if there are error conditions

2025-01-09 20:56 UTC, stepchud commented on config/routes.rb
> +    resources :evaluations, only: [:new]
option to nest this route under submissions instead

2025-01-09 22:08 UTC, stepchud commented on app/controllers/evaluations_controller.rb
> +      Evaluation.new
it might be better to attach the current_user to the new record here rather than passing their ID as a hidden param from the form submission
```suggestion
      Evaluation.new(user_id: current_user.id)
```

2025-01-13 17:59 UTC, stepchud commented on spec/requests/evaluations_spec.rb
> +      # TODO: Needs fix
what needs fix?

2025-01-13 18:31 UTC, cpreisinger commented on spec/requests/evaluations_spec.rb
> +      # TODO: Needs fix
I think this was old and I forgot to remove it. When I was having the issue with evaluation_scores failing uniqueness validation

2025-01-13 19:29 UTC, stepchud requested changes
I'll push a fix for the blockers

2025-01-13 19:29 UTC, stepchud commented on app/controllers/evaluations_controller.rb
> +# rubocop:disable all
won't block on this, but it's better to disable the specific cop that is failing than all of them. just in case we forget to re-enable or some other changes break different cops than the ClassLength one.

2025-01-13 19:29 UTC, stepchud commented on app/controllers/evaluations_controller.rb
> +      redirect_to new_submission_evaluation_path(@evaluator_submission_assignment.submission_id)
since the redirect triggers a fresh request/response cycle, you should use `flash[:alert]` instead of flash.now above

2025-01-13 19:29 UTC, stepchud commented on app/controllers/evaluations_controller.rb
> +      redirect_to new_submission_evaluation_path(@evaluator_submission_assignment.submission_id)
update flash.now => flash

2025-01-13 19:29 UTC, stepchud commented on app/controllers/evaluations_controller.rb
> +    @evaluation = Evaluation.find_by(id: params[:id])
this needs to load the evaluator_submission_assignment otherwise it always returns unauthorized (the specs for this request route aren't checking the response status)

2025-01-13 20:00 UTC, stepchud approved these changes
looks good to me

2025-01-14 00:57 UTC, merged